##################################################
# control_logic packaged IP (vhd-ips Make structure)
##################################################
PROJECT := $(shell basename "${PWD}")
MODULE := $(shell echo "${PROJECT}")
export PROJECT
export MODULE
include ../common.mk